### ISSUE TITLE
Installation: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

### ISSUE THREAD

**Issue by arborrow** [vuejsdevelopers/vuejs-poster-shop#1]
Following the instructions I was getting an error running npm install. To proceed, I had to delete npm-shrinkwrap.json and then do the npm install. What is the advantage of keeping the shrinkwrap version in the repository? It seems it might be better for non-darwin users to simply remove that file. Peace -Anthony

**Comment by arborrow** [comment]
p.s. - there was a fair amount of discussion on this issue at https://github.com/npm/npm/issues/14042

**Comment by vuejsdevelopers** [comment]
Thanks for this, I'll remove the shrinkwrap file from the repo.
