### ISSUE TITLE
index.js doesn't start up in either nodemon or node

### ISSUE THREAD

**Issue by tangst** [vuejsdevelopers/vuejs-poster-shop#2]
Anthony,
I'm on Mac Sierra, and I'm running into the exception problem when running npm run start.  Nodemon thinks the problem is in your index.js.  I have already tried deleting the node_modules folder and reinstalling. In addition, running node ./index.js  produces the same error message.  My Webstorm syntax linter is flagging the same => in your code.  I'm not sure if this is nodemon, node, or a problem with your code.

`/Users/Stephen/WebstormProjects/vuejs-poster-shop/index.js:26
 res.send(result.data.data.filter(item => !item.is_album && !item.nsfw &&
 ^^
SyntaxError: Unexpected token =>
 at exports.runInThisContext (vm.js:73:16)
 at Module._compile (module.js:443:25)
 at Object.Module._extensions..js (module.js:478:10)
 at Module.load (module.js:355:32)
 at Function.Module._load (module.js:310:12)
 at Function.Module.runMain (module.js:501:10)
 at startup (node.js:129:16)
 at node.js:814:3`

Here is the nodemon dump.

`node: v0.12.11
nodemon: 1.11.0
command: node /Users/Stephen/WebstormProjects/vuejs-poster-shop/node_modules/.bin/nodemon --dump
cwd: /Users/Stephen/WebstormProjects/vuejs-poster-shop
OS: darwin x64
--------------
{ run: false,
  system: { cwd: '/Users/Stephen/WebstormProjects/vuejs-poster-shop' },
  required: false,
  dirs: [ '/Users/Stephen/WebstormProjects/vuejs-poster-shop' ],
  timeout: 1000,
  options: 
   { dump: true,
     ignore: 
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules',
        re: /\.git|\.nyc_output|\.sass\-cache|bower_components|coverage|node_modules/ ],
     watch: [ '*.*', re: /.*\..*/ ],
     ignoreRoot: 
      [ '.git',
        '.nyc_output',
        '.sass-cache',
        'bower_components',
        'coverage',
        'node_modules' ],
     restartable: 'rs',
     colours: true,
     execMap: { py: 'python', rb: 'ruby' },
     stdin: true,
     runOnChangeOnly: false,
     verbose: false,
     stdout: true,
     execOptions: 
      { script: 'index.js',
        exec: 'node',
        args: [],
        scriptPosition: 0,
        nodeArgs: undefined,
        ext: 'js,json',
        env: {},
        execArgs: [] },
     monitor: 
      [ '*.*',
        '!/Users/Stephen/WebstormProjects/vuejs-poster-shop/.git/**/*',
        '!.nyc_output',
        '!.sass-cache',
        '!bower_components',
        '!coverage',
        '!/Users/Stephen/WebstormProjects/vuejs-poster-shop/node_modules/**/*' ] },
  signal: 'SIGUSR2',
  load: [Function],
  reset: [Function: reset],
  lastStarted: 0,
  loaded: [],
  watchInterval: null,
  command: 
   { raw: { executable: 'node', args: [ 'index.js' ] },
     string: 'node index.js' } }`

**Comment by vuejsdevelopers** [comment]
It's because your node version is too old. Upgrade to v4 or later and you shouldn't have a problem.

**Comment by tangst** [comment]
Thanks.  I upgraded to 0.6.11 and that made the error go away.

**Comment by vuejsdevelopers** [comment]
Great! The issue is because arrow functions didn't get support until v4 of node.
