### ISSUE TITLE
App Keeps Crashing

### ISSUE THREAD

**Issue by paul-javs** [vuejsdevelopers/vuejs-poster-shop#3]
I forked the repo, cloned it to my local, installed all necessary modules ran it and it just crashes. Here's what I get after typing 'npm run start'

> vuejs-poster-shop@1.0.0 start /Users/paul-macbook/GIT/udemy-vuejs-poster-store-app/vuejs-poster-shop
> nodemon ./index.js --ignore node_modules/ -e js,html,css

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./index.js`
/Users/paul-macbook/GIT/udemy-vuejs-poster-store-app/vuejs-poster-shop/node_modules/reload/lib/reload.js:37
    for (let conn of connections) {
         ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/paul-macbook/GIT/udemy-vuejs-poster-store-app/vuejs-poster-shop/index.js:38:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by anthonygore** [comment]
Hi, can you tell me what version of Node.js you have installed? If it's less than 6, that's likely to be the problem.

**Comment by tlubenov** [comment]
Hi,
I install all components up to date and everything looks just fine. i use YARN v1.0.1 NodeJS 6.11.3.
when dev server starts there is message for Deprecated Warning. Looks like parameters parsing update need to be done.

_Deprecated Warning: You supplied reload old arguments, please upgrade to the new parameters see: https://github.com/alallier/reload/tree/master#api-for-express_

"dependencies": {
    "axios": "^0.16.2",
    "body-parser": "^1.18.2",
    "dotenv": "^4.0.0",
    "express": "^4.16.1",
    "querystring": "^0.2.0",
    "scrollmonitor": "^1.2.3",
    "vue": "^2.4.4",
    "vue-resource": "^1.3.4"
  },
  "devDependencies": {
    "nodemon": "^1.12.1",
    "reload": "^2.2.2"
  }

**Comment by anthonygore** [comment]
How come in your devDependencies you have reload ^2.2.2? In the current version of the app it is ^1.1.0

https://github.com/vuejsdevelopers/vuejs-poster-shop/blob/master/package.json

Is there a reason you can't stick with v1?
