### ISSUE TITLE
why is different with your demo page?

### ISSUE THREAD

**Issue by fedalee** [vuejsdevelopers/vuejs-poster-shop#4]

**Comment by fedalee** [comment]
### install page
![default](https://user-images.githubusercontent.com/10650455/34456650-db27f4b4-edd6-11e7-83a3-84ec8024a4c9.PNG)

### demo page

![default](https://user-images.githubusercontent.com/10650455/34456661-1bad7914-edd7-11e7-98a0-8ae06a75deab.PNG)

**Comment by fedalee** [comment]
maybe  the reason is that I can not touch https://api.imgur.com/3/

**Comment by anthonygore** [comment]
Hi,

Sorry for the late reply. 

Yes, it's different because the source code here is incomplete, you need to fill out the rest yourself as part of the course!
