### ISSUE TITLE
Demo App is not working.

### ISSUE THREAD

**Issue by JeffCleverley** [vuejsdevelopers/vuejs-poster-shop#7]
http://vuejs-poster-shop.vuejsdevelopers.com/

Leads to an Application Error.

![screen shot 2018-03-31 at 6 02 24 pm](https://user-images.githubusercontent.com/25419360/38162150-8806b6b0-350e-11e8-853f-b82ec83bf52c.png)

**Comment by anthonygore** [comment]
My Heroku plan expired. I'll have this fixed ASAP. Sorry for the disruption.

**Comment by anthonygore** [comment]
Is fixed now.

**Comment by JeffCleverley** [comment]
Great thanks

**Comment by m4rii0** [comment]
It does not work as 30/04/2018

**Comment by anthonygore** [comment]
It's fixed now, sorry for the hassle again.
